services:
  - type: web
    name: pqc-app
    env: docker
    region: oregon  # or choose another region
    plan: free  # or choose a different plan
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
    dockerCommand: /bin/bash -c ". .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port 8000" 